# Generated by Django 3.2.9 on 2021-12-21 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='')),
                ('displayornot', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name of the movie: ')),
                ('movie_file', models.FileField(upload_to='', verbose_name='Upload the movie: ')),
                ('subtitle_file', models.FileField(upload_to='', verbose_name='Upload the subtitles file: ')),
                ('trailer_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload the trailer file: ')),
                ('poster_file', models.FileField(max_length=512, upload_to='posters', verbose_name='Upload a poster file: ')),
                ('releasedate', models.DateField(default=datetime.datetime.now, verbose_name='Select the date of release: ')),
                ('content_rating', models.CharField(max_length=16, verbose_name='Rating: ')),
                ('genre_tags', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, verbose_name='Movie description: ')),
                ('displayornot', models.BooleanField(default=True, verbose_name='Disable this checkbox to hide this movie from the website: ')),
                ('actors', models.CharField(max_length=512, verbose_name='Actors (seperate by comma): ')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='termsconditionlisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('terms', models.TextField()),
                ('privacypolicy', models.TextField()),
            ],
            options={
                'verbose_name': 'About, Terms and Privacy Policy',
                'verbose_name_plural': 'About, Terms and Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name of the show: ')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Airing start date: ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Airing end date (leave empty if running): ')),
                ('trailer_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload the trailer file: ')),
                ('poster_file', models.FileField(max_length=512, upload_to='posters', verbose_name='Upload a poster file: ')),
                ('releasedate', models.DateField(default=datetime.datetime.now, verbose_name='Select the date of release: ')),
                ('content_rating', models.CharField(max_length=16, verbose_name='Rating: ')),
                ('genre_tags', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, verbose_name='Show description: ')),
                ('displayornot', models.BooleanField(default=True, verbose_name='Disable this checkbox to hide this show from the website: ')),
                ('actors', models.CharField(max_length=512, verbose_name='Actors (seperate by comma): ')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='')),
                ('file2', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('air_date', models.DateField(default=datetime.datetime.now, verbose_name='Airing date: ')),
                ('episode_num', models.SmallIntegerField()),
                ('season_num', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, verbose_name='Episode description: ')),
                ('movie_file', models.FileField(upload_to='', verbose_name='Upload the episode: ')),
                ('subtitle_file', models.FileField(upload_to='', verbose_name='Upload the subtitles file: ')),
                ('displayornot', models.BooleanField(default=True, verbose_name='Disable this checkbox to hide this episode from the website: ')),
                ('views', models.IntegerField(default=0)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='episodes', to='content.tvshow')),
            ],
        ),
    ]
