# Generated by Django 3.2.9 on 2021-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20211221_2354'),
    ]

    operations = [

    ]
