# Generated by Django 3.2.9 on 2021-12-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20211221_2358'),
    ]

    operations = [

    ]
