# Generated by Django 3.2.9 on 2021-12-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_movie_movielink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movielink',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='OR | Enter the upload location url: '),
        ),
    ]
