# Generated by Django 3.2.9 on 2021-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_movie_movielink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movielink',
            field=models.CharField(blank=True, help_text='If a URL is mentioned even when a file is uploaded, then the uploaded file will be shown instead of the file on the URL.', max_length=512, null=True, verbose_name='OR | Enter the upload location url'),
        ),
    ]
