# Generated by Django 3.2.9 on 2022-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_movie_movielink'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsconditionlisting',
            name='contact',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsconditionlisting',
            name='faq',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsconditionlisting',
            name='pricing',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
