# Generated by Django 3.2.9 on 2022-01-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20220108_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='author',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
