# Generated by Django 3.2.9 on 2022-01-31 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_ebook_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name', to='content.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='Moviecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name', to='content.movie')),
            ],
        ),
    ]
