"""
Django settings for cipherflix project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys; sys.path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(f"####################################{ BASE_DIR / 'upload'}") 
FILEBROWSER_DIRECTORY = BASE_DIR / 'upload'
DIRECTORY = BASE_DIR / 'upload'
from filebrowser.sites import site
site.storage.location = BASE_DIR / 'upload'
site.directory = BASE_DIR / 'upload'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a_tj_zb7w#@+5cf)rdgte^!td)e2$jw6#ek8@kic43!(5t+85&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SITE_ID = 1

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.
USE_L10N = True

# If you set this to False, Django will not use timezone-aware datetimes.
USE_TZ = True
PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))

# add current progressbarupload app to pytho path
PROGRESSBARUPLOAD_ROOT = os.path.dirname(os.path.dirname(PROJECT_DIR))
if os.path.exists(os.path.join(os.path.dirname(PROJECT_DIR), 'progressbarupload')):
    sys.path.insert(0, PROGRESSBARUPLOAD_ROOT)
    print("progressbarupload")

PROGRESSBARUPLOAD_INCLUDE_JQUERY = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'progressbarupload',
    'content.apps.ContentConfig', # new
    'storages',
    'bootstrap4form', # Required for nicer formatting of forms with the default templates
    'crispy_forms',
    'django.contrib.messages',
    'django.contrib.sites',
    'cipherflix',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'taggit',
    'analytical',
    'subscriptions',
    'payments', 
    'dashboard',
]
SITE_ID = 1
CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'content.middleware.MyMiddleware',
]

ROOT_URLCONF = 'cipherflix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'templates', 'allauth')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cipherflix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'defaultdb',
        'USER': 'doadmin',
        'PASSWORD': 'hVALNoP9IosEmbh6',
        'HOST': 'db-postgresql-fra1-27219-do-user-9938300-0.b.db.ondigitalocean.com',
        'PORT': '25060',
    }
}
FILE_UPLOAD_HANDLERS = (
    "progressbarupload.uploadhandler.ProgressBarUploadHandler",
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
)
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COINBASE_COMMERCE_API_KEY = 'ebd1ab73-95ea-486b-8750-97631dca2b10'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "cipherflixstreaming@gmail.com"
EMAIL_HOST_PASSWORD = "TestAdmin@123"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Custom allauth settings
# Use email as the primary identifier
ACCOUNT_AUTHENTICATION_METHOD = 'email' 
ACCOUNT_EMAIL_REQUIRED = True

# Make email verification mandatory to avoid junk email accounts
ACCOUNT_EMAIL_VERIFICATION = 'none' 
ACCOUNT_USERNAME_REQUIRED = False
import os
STATIC_URL = '/static/'
STATIC_ROOT = '/cipherflix/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
FILEBROWSER_DIRECTORY = ""
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880 # make it 5Mb instead of 2Mb
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
LOGIN_REDIRECT_URL = '../../../../profile'

JAZZMIN_SETTINGS = {
    "site_title": "Cipherflix",
    "site_header": "Cipherflix",
    "site_brand": "Cipherflix",
    "site_logo": "assets/img/faviconcipherflix.png",
    "site_logo_classes": "img-circle",
    "site_icon": "assets/img/faviconcipherflix.png",
    "welcome_sign": "Welcome to Cipherflix",
    "copyright": "Cipherflix",
    "search_model": "auth.User",
}

# Set your currency type
DFS_CURRENCY_LOCALE = 'en_us'
DFS_ENABLE_ADMIN = True

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mysite/static'),
]

AWS_ACCESS_KEY_ID = 'QHDWE2SFFCRYB6P4ZTJ7'
AWS_SECRET_ACCESS_KEY = 'Ku3IX14D9DdgBKZxqno36+Wb0zLJdZ+gHYKxRpZSHzU'
AWS_STORAGE_BUCKET_NAME = 'cipherflixstorage'
AWS_S3_ENDPOINT_URL = 'https://fra1.digitaloceanspaces.com'

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

AWS_LOCATION = 'static'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATIC_URL = "https://%s/%s/" % (AWS_S3_ENDPOINT_URL, AWS_LOCATION)

DEFAULT_FILE_STORAGE = 'cipherflix.storage_backends.MediaStorage'  # <-- here is where we reference it

PAYMENT_HOST = 'localhost:8000'
PAYMENT_USES_SSL = False
PAYMENT_MODEL = 'cipherflix.Payment'
PAYMENT_VARIANTS = {
    'default': ('payments.dummy.DummyProvider', {})}